version: '3.8'
services:
  news-aggregator-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=news_aggregator
    volumes:
      - ./db-data/pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  news-aggregator-pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - news-aggregator-postgres

  news-aggregator-redis:
    image: redis:latest
    ports:
      - '6378:6379'
    expose:
      - '6379'
    restart: always

  news-aggregator-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      POSTGRES_DB: news_aggregator
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - /data/db

  news-aggregator-server:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - news-aggregator-postgres
      - news-aggregator-mongo
      - news-aggregator-redis

  news-aggregator-client:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - news-aggregator-server